### PR TITLE
Remove pre-release license content

### PR DESCRIPTION
**Pull request by whmii**

### CODE REVIEW

**Comment by gabebw** [comment]
I'm glad we're removing this. While you're in there, a few more things:

1) How about noting that the license is the MIT license on the first line? Just changing "LICENSE" to "MIT License" should do it

2) The wording is kind of odd:

>  Permission is hereby granted, free of charge, to any employee of thoughtbot LLC. of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The first sentence in particular reads like it was copy-pasted. Why are we restricting the license to "thoughtbot employees"? Can we just use the original text of the MIT License from http://choosealicense.com/licenses/mit/ ?

**Comment by mike-burns** [comment]
The MIT license LGTM.

**Comment by whmii** [comment]
woot

**Comment by whmii** [comment]
:beers:

**Pull request merged**
