### PR TITLE
Redesign padlock to improve consistency with group [core-014-a]

### PR DESCRIPTION
**Pull request by whmii**

### CODE REVIEW

**Comment by ohaicristina** [comment]
I'm digging the redesign. Maybe throw in a screenshot in the description of this with other illustrations from the group so we can see it in context?

**Comment by whmii** [comment]
screen shot 2015-10-29 at 1 59 31 pm

**Comment by ColeTownsend** [comment]
this is nifty, good looks!

**Comment by whmii** [comment]
longshadow was :scissors:

**Pull request merged**
